version: '2'
services:
    garage-app:
        image: garage
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://garage-mysql:3306/garage?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://garage-elasticsearch:9200
        ports:
            - 8080:8080
    garage-mysql:
        extends:
            file: mysql.yml
            service: garage-mysql
    garage-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: garage-elasticsearch
